### ISSUE TITLE
flake8

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/TJPCov#10]
Feelings about flaking the code? Better earlier than later, right?

**Comment by sukhdeep2** [comment]
I think you mean linting the code? :) There is a whole other thing with `flake tests'!

I do not have any strong feelings about this. We should aim to catch any logical errors in the code via the tests we design. So the primary advantage I can see with linting is in terms of imposing a stylistic guide. I'm not sure how strongly do we want to do so. Many of stylistic choices tend to be subjective and I tend to favor a more relaxed approach in this regard as long as it does not impede the readability of the code. 

Is there any strong reason for us to have it?

**Comment by joezuntz** [comment]
I would suggest just periodically running the `black` command, which decides a linting for you.  Then you don't necessarily have to require it in PRs but can just run it whenever you feel like it.
