### ISSUE TITLE
dNdz computation needed?

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/TJPCov#12]
The redshift distribution is given in the sacc file with the rest of the data.
https://github.com/LSSTDESC/TJPCov/blob/a0c23af6c9d9ee462427aca1eb71b94a21db3d42/tjpcov/main.py#L373-L375

 Why don't use it directly?

**Comment by sukhdeep2** [comment]
I agree. Line 374 and 375 are unnecessary here. Reason to use 374 will if the CCL did not normalize dNdz. As per a comment later (line 381), it does normalize dNdz so we do not need to do so.
