### ISSUE TITLE
Managing GitHub Access to this Repo

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/TJPCov#14]
Hi!  We have a new contributor working with @damonge, @carlosggarcia who needs access to this repo.  How is membership in this repo managed?  I see that LSS and WL have access and that seems to be the primary way people are added in.  LSS is a "special" category managed by the DESC group manager - I can add people there directly.  Is that the correct thing to do in this case? Is WL appropriate?
Do we need/want to set up a tjpcov-developers group to handle other contributors or is that unnecessary?

**Comment by damonge** [comment]
I think either LSS or WL would be appropriate in this case, with no preference for one or the other as long as Carlos can get access.

**Comment by heather999** [comment]
I've added Carlos to the lsst-desc-lss group, which will trigger their membership in the LSS GitHub group.  That might take a couple of hours to take effect - but I'll check on it in a bit and let Carlos know when membership is all set.

**Comment by damonge** [comment]
Thanks a lot Heather!

**Comment by heather999** [comment]
Looks like Carlos is all set and is now in the LSS GitHub group.
