### ISSUE TITLE
Allow hdf5 files for mask paths to work with TXPipe

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/TJPCov#24]
TXPipe is using `hdf5` files to pass the masks. We should allow that format, as well. Also, when we allow to use a dictionary to initialize the class, we could also pass the open file directly.

**Comment by joezuntz** [comment]
If it's easier TXPipe can just read the mask directly and pass it to you.  Otherwise you can load these with:
```
import txpipe
with txpipe.data_types.MapsFile(filename, "r") as f:
    m = f.read_map("mask")
```

**Comment by carlosggarcia** [comment]
That's quite convenient! In fact, as you say, when using the dictionary as input, we can pass the mask directly. My worry was when you use the yml file and have to point to some file to read the mask from.
