### ISSUE TITLE
[suggestion] Allow NaMaster to be an optional dependency

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TJPCov#58]
[suggestion] As of now, `NaMaster` is required to `import tjpcov`. A potential enhancement could be to import namaster only inside of the classes that use it. What do you think @carlosggarcia? Please feel free to disregard if you think this is something that nobody is going to use.

**Comment by carlosggarcia** [comment]
It shouldn't be required. Are you using the last version of TJPCov? I have only found `pymaster` in `tjpcov/covariance_fourier_gaussian_nmt.py`.

**Comment by fjaviersanchez** [comment]
thanks! yeah, I went ahead without thinking and just did `import tjpcov` in a fresh environment and the error did pop up with the latest master. However, I guess this is not the intended usage. I'll go ahead and close this :)

**Comment by carlosggarcia** [comment]
Exactly. At the moment (it can change if people don't like it), users should use the `CovarianceCalculator` class. So you would do `from tjpcov.covariance_calculator import CovarianceCalculator`.

**Comment by carlosggarcia** [comment]
@fjaviersanchez I've had a closer look and the culprits are the imports in `__init__.py`. I think they are not needed. I'll fix this.
