### ISSUE TITLE
 parse: use yaml.safe_load instead of jinja2?

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/TJPCov#8]
I'm not sure what role `jinja2` plays in the parser at
https://github.com/LSSTDESC/TJPCov/blob/ed1e4c8cf3e0385b749ae83bc4ad2b1b70210215/tjpcov/parser.py#L25
Why not loading the yaml file directly with `yaml.safe_load(fp)`? That would remove a dependency.

**Comment by sukhdeep2** [comment]
I believe this came from the code we copied from Firecrown. If other parts of DESC pipeline are using jinja, then I will recommend keeping it. I am not up to date on other pipelines however and will let @felipeaoli make a call on this.
