### ISSUE TITLE
Require python 3.8

### ISSUE THREAD

**Issue by mattkwiecien** [LSSTDESC/TJPCov#85]
SACC would like to update to require python 3.8 or above.  Currently we require 3.7, but I don't think 3.8 would break anything.

**Comment by mattkwiecien** [comment]
Spun up a new conda environment with python 3.8 and installed tjpcov.  Ran all the tests and all tests passed.  Unless there's some edge cases I think we should be good to upgrade. @carlosggarcia @felipeaoli

**Comment by eacharles** [comment]
So, FWIW, in RAIL we are requiring 3.8, 3.9 and 3.10 in our test matrix.   I see that 3.11 is out there already.   Might be worth testing against at least 3.9 and 3.10…

-e

**Comment by mattkwiecien** [comment]
Good idea!  I'll check those as well, best to stay up to date as much as we can

**Comment by mattkwiecien** [comment]
All tests still pass for 3.8, 3.9, 3.10, and 3.11.  Will upgrade to 3.8 in a PR
