### ISSUE TITLE
Lock issue when working at NERSC

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TJPCov#94]
Hi everyone,

When executing TJPCov from my $HOME directory at Perlmutter I get a `OS Error: 524` that had to do with the inability to lock files in the regular NERSC filesystem (I think it would also raise if working from `/global/cfs/`). Switching the line: https://github.com/LSSTDESC/TJPCov/blob/master/tjpcov/tools.py#L90 from 

`self.fp = open("./lockfile.lock", "wb")`

to 

`self.fp = open("/tmp/lockfile.lock", "wb")`

solves the problem for me at NERSC (I think that executing from $SCRATCH or pointing to $SCRATCH would also work). Is this a me problem or can anyone else reproduce this?

Thanks in advance!

**Comment by mattkwiecien** [comment]
@fjaviersanchez Thanks for pointing this out and sorry about the delay!  I believe this lock is no longer necessary as we fixed the underlying issue that it was attempting to address.  I will remove this and that should fix the issue.
