### ISSUE TITLE
Plans to support CCL >=2.8.0?

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/TJPCov#96]
I've been looking to help the forecasts folks set up an environment with augur, TJPCov, and firecrown, but then noticed this [requirement on CCL](https://github.com/LSSTDESC/TJPCov/blob/28e16cc434ad180c001a4558b25a6d3cc03c874c/pyproject.toml#L30) 
Meanwhile recent [versions of firecrown require a CCL feature in 2.8.0](https://github.com/LSSTDESC/firecrown/blob/c2a6b759e1385b88e3c23924c337f3628649db2f/firecrown/modeling_tools.py#L22)
And augur requires firecrown.

This makes it difficult to support all 3 in one conda environment - though I suspect others have already run into this problem. Are there active plans to update TJPCov to use a more recent CCL?

**Comment by carlosggarcia** [comment]
Sounds like a good plan for the Sprint week

**Comment by carlosggarcia** [comment]
Closed by #97
